services:
  nginx:
    image: nginx
    volumes:
      - ./infrastructure/nginx/snippets/oauth2.snippet.template:/etc/nginx/templates/oauth2.snippet.template:ro
      - ./services/demo/deploy/demo.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./infrastructure/oauth2-proxy/deploy/oauth2-proxy.conf.template:/etc/nginx/templates/oauth2-proxy.conf.template:ro
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80
      - EXTERNAL_HOST=learn.edu
      - EXTERNAL_PORT=8090

  oauth2-proxy:
    build:
      context: ./infrastructure/oauth2-proxy
    volumes:
      - ./infrastructure/oauth2-proxy/oauth2-proxy.conf.template:/root/oauth2-proxy.conf.template
    
    environment:
      - EXTERNAL_PORT=8090
      - EXTERNAL_HOST=learn.edu
      - OAUTH2_PROXY_COOKIE_SECRET=0123456789012345
      - OAUTH2_PROXY_CLIENT_SECRET="TODO"
      - OAUTH2_PROXY_CLIENT_ID=73666830365-1bq7s9no6juesg9kjh8p11j1nduueao8.apps.googleusercontent.com

  demo:
    build:
      context: ./services/demo

    