services:
  nginx:
    image: nginx
    volumes:
      - ./infrastructure/nginx/snippets/oauth2.snippet.template:/etc/nginx/templates/oauth2.snippet.template:ro
      - ./infrastructure/oauth2-proxy/deploy/oauth2-proxy.conf.template:/etc/nginx/templates/oauth2-proxy.conf.template:ro
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/agentarena/deploy/nginx/agentarena.conf.template:/etc/nginx/templates/agentarena.conf.template:ro
      # - ./services/demo/deploy/demo.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - taxis
      - agentarena
      # - demo
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80
      - EXTERNAL_HOST=${EXTERNAL_HOST}
      - EXTERNAL_PORT=${EXTERNAL_PORT}

  oauth2-proxy:
    build:
      context: ./infrastructure/oauth2-proxy
    volumes:
      - ./infrastructure/oauth2-proxy/oauth2-proxy.conf.template:/root/oauth2-proxy.conf.template:ro
    
    environment:
      - EXTERNAL_HOST=${EXTERNAL_HOST}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}

  taxis:
    build:
      context: ./internal/taxis
    volumes:
    - ./infrastructure/taxis/taxis.conf:/app/taxis.conf:ro
    - ./groups.yml:/app/groups.yml:ro
    depends_on:
      - oauth2-proxy

  # demo:
  #   build:
  #     context: ./services/demo
  
  postgres:
    image: postgres:latest
    volumes: 
      - ./services/agentarena/db/schema.sql:/docker-entrypoint-initdb.d/01.sql
      # Uncomment the following volume to add mock data
      - ./services/agentarena/db/mocks/0001.sql:/docker-entrypoint-initdb.d/02.sql
    environment:
      POSTGRES_PASSWORD: agentarena
      POSTGRES_DB: agentarena
      POSTGRES_USER: agentarena
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agentarena -d agentarena"]
      interval: 5s
      timeout: 5s
      retries: 10

  agentarena:
    build:
      context: ./services/agentarena
    environment:
      AGENTARENA_PG_DATABASE: agentarena
      AGENTARENA_PG_HOST: postgres
      AGENTARENA_PG_PORT: 5432
      AGENTARENA_PG_USERNAME: agentarena
      AGENTARENA_PG_PASSWORD: agentarena
      AGENTARENA_OLLAMA_URL: http://ollama:11434

    depends_on:
      postgres:
        condition: service_healthy
      ollama-pull-gemma:
        condition: service_completed_successfully

  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama

    healthcheck:
      test: ["CMD-SHELL", "ollama list"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama-pull-gemma:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    entrypoint: /bin/sh
    command: "-c 'sleep 5 && ollama pull gemma3:1B'"
    depends_on:
      ollama:
        condition: service_healthy