// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Agent struct {
	AgentID int32
	Name    string
}

type AgentConfig struct {
	AgentID      int32
	SystemPrompt string
}

type Conversation struct {
	ConversationID int32
	Name           sql.NullString
}

type Message struct {
	MessageID      int32
	ConversationID int32
	Content        sql.NullString
	SentAt         sql.NullTime
	AuthorType     sql.NullString
	AgentID        sql.NullInt32
	UserID         sql.NullString
}
