// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AgentPermissionType string

const (
	AgentPermissionTypeManage   AgentPermissionType = "manage"
	AgentPermissionTypeInteract AgentPermissionType = "interact"
)

func (e *AgentPermissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentPermissionType(s)
	case string:
		*e = AgentPermissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentPermissionType: %T", src)
	}
	return nil
}

type NullAgentPermissionType struct {
	AgentPermissionType AgentPermissionType `json:"agentPermissionType"`
	Valid               bool                `json:"valid"` // Valid is true if AgentPermissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentPermissionType) Scan(value interface{}) error {
	if value == nil {
		ns.AgentPermissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentPermissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentPermissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentPermissionType), nil
}

type Agent struct {
	AgentID int32  `json:"agentId"`
	Name    string `json:"name"`
}

type AgentConfig struct {
	AgentID      int32  `json:"agentId"`
	SystemPrompt string `json:"systemPrompt"`
}

type Conversation struct {
	ConversationID int32          `json:"conversationId"`
	Name           sql.NullString `json:"name"`
}

type GroupAgentPermission struct {
	GroupID string              `json:"groupId"`
	AgentID int32               `json:"agentId"`
	Ability AgentPermissionType `json:"ability"`
}

type Message struct {
	MessageID      int32          `json:"messageId"`
	ConversationID int32          `json:"conversationId"`
	Content        sql.NullString `json:"content"`
	SentAt         sql.NullTime   `json:"sentAt"`
	AuthorType     sql.NullString `json:"authorType"`
	AgentID        sql.NullInt32  `json:"agentId"`
	UserID         sql.NullString `json:"userId"`
}

type UserAgentPermission struct {
	UserID  string              `json:"userId"`
	AgentID int32               `json:"agentId"`
	Ability AgentPermissionType `json:"ability"`
}
