// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const getAgentFull = `-- name: GetAgentFull :one
select agents.agent_id, agents.name, agent_configs.system_prompt
from agents join agent_configs on agents.agent_id = agent_configs.agent_id
where agents.agent_id=$1
limit 1
`

type GetAgentFullRow struct {
	AgentID      int32  `json:"agentId"`
	Name         string `json:"name"`
	SystemPrompt string `json:"systemPrompt"`
}

func (q *Queries) GetAgentFull(ctx context.Context, agentID int32) (GetAgentFullRow, error) {
	row := q.db.QueryRow(ctx, getAgentFull, agentID)
	var i GetAgentFullRow
	err := row.Scan(&i.AgentID, &i.Name, &i.SystemPrompt)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
select m.message_id, m.content, m.sent_at, m.author_type, m.agent_id, m.user_id
from messages as m
where m.conversation_id = $1
order by m.sent_at desc, m.message_id asc
`

type GetConversationMessagesRow struct {
	MessageID  int32           `json:"messageId"`
	Content    string          `json:"content"`
	SentAt     sql.NullTime    `json:"sentAt"`
	AuthorType NullMessageType `json:"authorType"`
	AgentID    sql.NullInt32   `json:"agentId"`
	UserID     sql.NullString  `json:"userId"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, conversationID int32) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.SentAt,
			&i.AuthorType,
			&i.AgentID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversations = `-- name: GetConversations :many
select conversation_id, name
from conversations
where user_id = $1
`

type GetConversationsRow struct {
	ConversationID int32  `json:"conversationId"`
	Name           string `json:"name"`
}

func (q *Queries) GetConversations(ctx context.Context, userID string) ([]GetConversationsRow, error) {
	rows, err := q.db.Query(ctx, getConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsRow
	for rows.Next() {
		var i GetConversationsRow
		if err := rows.Scan(&i.ConversationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAgentPermission = `-- name: HasAgentPermission :one
SELECT EXISTS (
    SELECT 1 FROM user_agent_permissions uap
    WHERE uap.user_id = $1 
      AND uap.agent_id = $2 
      AND uap.ability = $3
    
    UNION ALL
    
    SELECT 1 FROM group_agent_permissions
    WHERE group_id = ANY($4::text[])
      AND agent_id = $2 
      AND ability = $3
)
`

type HasAgentPermissionParams struct {
	UserID   string           `json:"userId"`
	AgentID  int32            `json:"agentId"`
	Ability  AgentAbilityType `json:"ability"`
	GroupIds []string         `json:"groupIds"`
}

func (q *Queries) HasAgentPermission(ctx context.Context, arg HasAgentPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAgentPermission,
		arg.UserID,
		arg.AgentID,
		arg.Ability,
		arg.GroupIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const startedConversation = `-- name: StartedConversation :one
select exists (
    select 1
    from conversations
    where conversation_id = $1 AND user_id = $2
)
`

type StartedConversationParams struct {
	ConversationID int32  `json:"conversationId"`
	UserID         string `json:"userId"`
}

func (q *Queries) StartedConversation(ctx context.Context, arg StartedConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, startedConversation, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
