// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const getAgent = `-- name: GetAgent :one
select agent_id, name
from agents
where agent_id=$1
limit 1
`

func (q *Queries) GetAgent(ctx context.Context, agentID int32) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, agentID)
	var i Agent
	err := row.Scan(&i.AgentID, &i.Name)
	return i, err
}

const getAgentConfig = `-- name: GetAgentConfig :one
select agent_id, system_prompt
from agent_configs
where agent_id=$1
limit 1
`

func (q *Queries) GetAgentConfig(ctx context.Context, agentID int32) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfig, agentID)
	var i AgentConfig
	err := row.Scan(&i.AgentID, &i.SystemPrompt)
	return i, err
}
