email_domain = "@ucr.edu"
client_id = 73666830365-1bq7s9no6juesg9kjh8p11j1nduueao8.apps.googleusercontent.com
reverse_proxy = true
set_xauthrequest= true
redirect-url = http://${HOST}:${PORT}/${OAUTH2_PROXY_REDIRECT_PATH}
