host = 0.0.0.0
port = 14812

auth_proxy_url = http://oauth2-proxy:4180/oauth2/auth
groups_header = X-Groups

auth_proxy_user_id_header = X-Auth-Request-Email
root_path = /taxis

user_id_header = X-Email

watch = false

