// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"

	"github.com/jackc/pgtype"
)

const createConversationWithInitialMessage = `-- name: CreateConversationWithInitialMessage :one
WITH new_conv AS (
    INSERT INTO conversations (user_id, name, active_agent_id)
    VALUES ($2, $3, $4)
    RETURNING conversation_id, user_id, active_agent_id
)
INSERT INTO messages (
    conversation_id, 
    content, 
    message_type, 
    user_id, 
    agent_id
)
SELECT 
    new_conv.conversation_id, 
    $1, 
    'user',
    new_conv.user_id, 
    NULL            -- agent_id is null for user messages
FROM new_conv
RETURNING conversation_id, message_id
`

type CreateConversationWithInitialMessageParams struct {
	MessageContent   string        `json:"messageContent"`
	UserID           string        `json:"userId"`
	ConversationName string        `json:"conversationName"`
	AgentID          sql.NullInt32 `json:"agentId"`
}

type CreateConversationWithInitialMessageRow struct {
	ConversationID int32 `json:"conversationId"`
	MessageID      int32 `json:"messageId"`
}

func (q *Queries) CreateConversationWithInitialMessage(ctx context.Context, arg CreateConversationWithInitialMessageParams) (CreateConversationWithInitialMessageRow, error) {
	row := q.db.QueryRow(ctx, createConversationWithInitialMessage,
		arg.MessageContent,
		arg.UserID,
		arg.ConversationName,
		arg.AgentID,
	)
	var i CreateConversationWithInitialMessageRow
	err := row.Scan(&i.ConversationID, &i.MessageID)
	return i, err
}

const getAgent = `-- name: GetAgent :one
select a.agent_id, a.name, a.agent_class_id, a.config
from agents a
where a.agent_id=$1
limit 1
`

type GetAgentRow struct {
	AgentID      int32        `json:"agentId"`
	Name         string       `json:"name"`
	AgentClassID string       `json:"agentClassId"`
	Config       pgtype.JSONB `json:"config"`
}

func (q *Queries) GetAgent(ctx context.Context, agentID int32) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, agentID)
	var i GetAgentRow
	err := row.Scan(
		&i.AgentID,
		&i.Name,
		&i.AgentClassID,
		&i.Config,
	)
	return i, err
}

const getAgentConfigFromConversationId = `-- name: GetAgentConfigFromConversationId :one
select a.config, a.agent_id, a.agent_class_id
from agents as a join conversations as c
    on a.agent_id = c.active_agent_id
where c.conversation_id = $1
limit 1
`

type GetAgentConfigFromConversationIdRow struct {
	Config       pgtype.JSONB `json:"config"`
	AgentID      int32        `json:"agentId"`
	AgentClassID string       `json:"agentClassId"`
}

func (q *Queries) GetAgentConfigFromConversationId(ctx context.Context, conversationID int32) (GetAgentConfigFromConversationIdRow, error) {
	row := q.db.QueryRow(ctx, getAgentConfigFromConversationId, conversationID)
	var i GetAgentConfigFromConversationIdRow
	err := row.Scan(&i.Config, &i.AgentID, &i.AgentClassID)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
select m.message_id, m.content, m.sent_at, m.message_type, m.agent_id, m.user_id
from messages as m
where m.conversation_id = $1
order by m.sent_at asc, m.message_id asc
`

type GetConversationMessagesRow struct {
	MessageID   int32          `json:"messageId"`
	Content     string         `json:"content"`
	SentAt      sql.NullTime   `json:"sentAt"`
	MessageType MessageType    `json:"messageType"`
	AgentID     sql.NullInt32  `json:"agentId"`
	UserID      sql.NullString `json:"userId"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, conversationID int32) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.SentAt,
			&i.MessageType,
			&i.AgentID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationMetadata = `-- name: GetConversationMetadata :one
select conversation_id, name, active_agent_id
from conversations c
where c.conversation_id = $1
limit 1
`

type GetConversationMetadataRow struct {
	ConversationID int32         `json:"conversationId"`
	Name           string        `json:"name"`
	ActiveAgentID  sql.NullInt32 `json:"activeAgentId"`
}

func (q *Queries) GetConversationMetadata(ctx context.Context, conversationID int32) (GetConversationMetadataRow, error) {
	row := q.db.QueryRow(ctx, getConversationMetadata, conversationID)
	var i GetConversationMetadataRow
	err := row.Scan(&i.ConversationID, &i.Name, &i.ActiveAgentID)
	return i, err
}

const getUserConversations = `-- name: GetUserConversations :many
select c.conversation_id, c.name
from conversations c
left join messages m on c.conversation_id = m.conversation_id
where c.user_id = $1
group by c.conversation_id, c.name
order by MAX(m.sent_at) desc nulls last
`

type GetUserConversationsRow struct {
	ConversationID int32  `json:"conversationId"`
	Name           string `json:"name"`
}

func (q *Queries) GetUserConversations(ctx context.Context, userID string) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(&i.ConversationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAgentPermission = `-- name: HasAgentPermission :one
SELECT EXISTS (
    SELECT 1 FROM user_agent_permissions uap
    WHERE uap.user_id = $1 
      AND uap.agent_id = $2 
      AND uap.ability = $3
    
    UNION ALL
    
    SELECT 1 FROM group_agent_permissions
    WHERE group_id = ANY($4::text[])
      AND agent_id = $2 
      AND ability = $3
)
`

type HasAgentPermissionParams struct {
	UserID   string           `json:"userId"`
	AgentID  int32            `json:"agentId"`
	Ability  AgentAbilityType `json:"ability"`
	GroupIds []string         `json:"groupIds"`
}

func (q *Queries) HasAgentPermission(ctx context.Context, arg HasAgentPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAgentPermission,
		arg.UserID,
		arg.AgentID,
		arg.Ability,
		arg.GroupIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const postMessageToConversation = `-- name: PostMessageToConversation :one
insert into messages (conversation_id, content, message_type, agent_id, user_id) values
($1, $2, $3, $4, $5)
returning message_id as message_id, content as content
`

type PostMessageToConversationParams struct {
	ConversationID int32          `json:"conversationId"`
	Content        string         `json:"content"`
	MessageType    MessageType    `json:"messageType"`
	AgentID        sql.NullInt32  `json:"agentId"`
	UserID         sql.NullString `json:"userId"`
}

type PostMessageToConversationRow struct {
	MessageID int32  `json:"messageId"`
	Content   string `json:"content"`
}

func (q *Queries) PostMessageToConversation(ctx context.Context, arg PostMessageToConversationParams) (PostMessageToConversationRow, error) {
	row := q.db.QueryRow(ctx, postMessageToConversation,
		arg.ConversationID,
		arg.Content,
		arg.MessageType,
		arg.AgentID,
		arg.UserID,
	)
	var i PostMessageToConversationRow
	err := row.Scan(&i.MessageID, &i.Content)
	return i, err
}

const startedConversation = `-- name: StartedConversation :one
select exists (
    select 1
    from conversations
    where conversation_id = $1 AND user_id = $2
)
`

type StartedConversationParams struct {
	ConversationID int32  `json:"conversationId"`
	UserID         string `json:"userId"`
}

func (q *Queries) StartedConversation(ctx context.Context, arg StartedConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, startedConversation, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAgentWithManagerAndInteractorUnchecked = `-- name: createAgentWithManagerAndInteractorUnchecked :one
with new_agent as (
    insert into agents (name, agent_class_id, config)
    values ($1, $2, $3)
    returning agent_id
)
insert into user_agent_permissions (user_id, agent_id, ability)
select
    $4 AS user_id, 
    new_agent.agent_id AS agent_id, 
    'manage'::agent_ability_type AS ability
from new_agent
union all
select $4, new_agent.agent_id, 'interact'
from new_agent
returning agent_id
`

type createAgentWithManagerAndInteractorUncheckedParams struct {
	Name         string       `json:"name"`
	AgentClassID string       `json:"agentClassId"`
	Config       pgtype.JSONB `json:"config"`
	UserID       string       `json:"userId"`
}

func (q *Queries) createAgentWithManagerAndInteractorUnchecked(ctx context.Context, arg createAgentWithManagerAndInteractorUncheckedParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAgentWithManagerAndInteractorUnchecked,
		arg.Name,
		arg.AgentClassID,
		arg.Config,
		arg.UserID,
	)
	var agent_id int32
	err := row.Scan(&agent_id)
	return agent_id, err
}

const setAgentConfigUnchecked = `-- name: setAgentConfigUnchecked :exec
update agents
set config = $2
where agent_id = $1
`

type setAgentConfigUncheckedParams struct {
	AgentID int32        `json:"agentId"`
	Config  pgtype.JSONB `json:"config"`
}

func (q *Queries) setAgentConfigUnchecked(ctx context.Context, arg setAgentConfigUncheckedParams) error {
	_, err := q.db.Exec(ctx, setAgentConfigUnchecked, arg.AgentID, arg.Config)
	return err
}
